id: P009109
initial_creation_type: ocr
source_metadata:
  id: bdr:W30187
  title: གསང་སྔགས་ནང་གི་ལམ་རིམ་རྒྱ་ཆེར་འགྲེལ་པ་སངས་རྒྱས་གཉིས་པའི་དགོངས་རྒྱན
  author: ''
  volumes:
    bbe7edd4759247e18b0ada54f43daa6e:
      image_group_id: I5966
      title: ''
      volume_number: 1
      total_pages: 936
      base_file: v001.txt
