id: IDCFE248F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:42:57+00:00'
last_modified: '2022-06-08T08:41:12.789494+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30187
  title: གསང་སྔགས་ནང་གི་ལམ་རིམ་རྒྱ་ཆེར་འགྲེལ་པ་སངས་རྒྱས་གཉིས་པའི་དགོངས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CF9B:
      image_group_id: I5966
      title: ''
      total_pages: 936
      order: 1
      base_file: CF9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
