id: IDCFE248F
legacy_id: P009109
ocr_import_info:
  bdrc_scan_id: W30187
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:37:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:25:14.264888+00:00'
last_modified: 2022-09-03 19:25:23.852399
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30187
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30187
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་སྔགས་ནང་གི་ལམ་རིམ་རྒྱ་ཆེར་འགྲེལ་པ་སངས་རྒྱས་གཉིས་པའི་དགོངས་རྒྱན།
  author: མྱང་ཉི་མ་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9612213808787233
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5966:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5966
      total_pages: 936
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5966.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9612213808787233
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
